from enum import StrEnum


class RoutingOutcome(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_DOCUMENTS = "REQUEST_DOCUMENTS"
    ESCALATE_TO_UNDERWRITER = "ESCALATE_TO_UNDERWRITER"


class LoanType(StrEnum):
    CONVENTIONAL = "CONVENTIONAL"
    FHA = "FHA"
    VA = "VA"
    JUMBO = "JUMBO"


class EmploymentStatus(StrEnum):
    EMPLOYED = "EMPLOYED"
    SELF_EMPLOYED = "SELF_EMPLOYED"
    RETIRED = "RETIRED"
    UNEMPLOYED = "UNEMPLOYED"


class PropertyType(StrEnum):
    SINGLE_FAMILY = "SINGLE_FAMILY"
    CONDO = "CONDO"
    MULTI_FAMILY = "MULTI_FAMILY"
    COMMERCIAL = "COMMERCIAL"


class DocumentType(StrEnum):
    BANK_STATEMENT = "BANK_STATEMENT"
    TAX_RETURN = "TAX_RETURN"
    EMPLOYMENT_VERIFICATION = "EMPLOYMENT_VERIFICATION"
    APPRAISAL = "APPRAISAL"
    CREDIT_REPORT = "CREDIT_REPORT"
    PAY_STUB = "PAY_STUB"
    GOVERNMENT_ID = "GOVERNMENT_ID"
